name = "math-wizards-gemini"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Environment variables and secrets
# Set secrets using: wrangler secret put GEMINI_API_KEY
# Do not commit API keys to version control!

# Example of setting the secret:
# cd workers/gemini
# wrangler secret put GEMINI_API_KEY
# (then paste your Google AI Studio API key)
