name = "keyword-detector"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Uncomment to run on a custom domain
# routes = [
#   { pattern = "keywords.example.com/*", zone_name = "example.com" }
# ]

# Development configuration
[env.development]
name = "keyword-detector-dev"

# Production configuration
[env.production]
name = "keyword-detector-prod"
